[versions]
# Define versions in one place
spock = "2.4-groovy-4.0"
junit = "6.0.2"

[libraries]
# Define the coordinates
spock-core = { group = "org.spockframework", name = "spock-core", version.ref = "spock" }
junit-launcher = { group = "org.junit.platform", name = "junit-platform-launcher", version.ref = "junit" }

[bundles]
# Group test dependencies together
testing = ["spock-core", "junit-launcher"]
