plugins {
    id 'groovy'
}

repositories {
    mavenCentral()
    maven { url = 'https://repo.jenkins-ci.org/public/' }
}

dependencies {
    implementation project(':')

    // Using the bundle from the gradle/lib.versions.toml file
    compileOnly libs.bundles.compile
    testImplementation libs.bundles.testing
    testRuntimeOnly libs.bundles.testrun 
}

sourceSets {
    main {
        groovy { srcDirs = ['src/main/groovy'] }
    }
    test {
        groovy { srcDirs = ['src/test/groovy'] }
        java { srcDirs = ['src/test/java'] }
    }
}

test {
    useJUnitPlatform()
    testLogging {
        events 'passed', 'skipped', 'failed'
    }
}
